### ISSUE TITLE
Crashes when I try to Edit SSB Info 

### ISSUE THREAD

**Issue by Yawrf** [HiddenRambler/TagMo#29]
Running Android 6.0.1 and the latest full release, every time I hit the Edit SSB Info button, it crashes. Anyone know why? (Or if it's known and being fixed, I didn't see it among the issues, but I may just be blind)

**Comment by lozamiibo** [comment]
Same issue here...

**Comment by azsde** [comment]
It only works when scanning a real amiibo, not when loading a .bin file.

**Comment by lozamiibo** [comment]
Thanks for the info!

**Comment by Bombastisch** [comment]
Still doesn't work....   (Nexus 5X,  Lineage OS, Android 7.0.1)

I'm really interested in this feature but it just won't work!

**Comment by Bombastisch** [comment]
Okay, my amiibo was kinda broken? It works now, no problems anymore

**Comment by smokeandlights** [comment]
I am also having the same problem. I can scan and load just fine, but if I try to scan an amiibo and edit ssb data or view hex, the app crashes. I haven't tried to write tags yet. Android 6.0.1, Samsung Galaxy S5 (G900V).

**Comment by smokeandlights** [comment]
This seems to be fixed in 2.4.0 . Thanks!
