### ISSUE TITLE
Blackberry Q10 nfc not supported 

### ISSUE THREAD

**Issue by Sutts1974** [HiddenRambler/TagMo#46]
Nfc turned on 
Tagmo 2.3.4 installed 

I can upload both keys and tag 

Error message saying NFC not supported on right side beneath 3 white dots.

**Comment by HiddenRambler** [comment]
Can you install the NXP Tag info app https://play.google.com/store/apps/details?id=com.nxp.taginfolite and see if NFC works for it?

**Comment by HiddenRambler** [comment]
I'm closing this as there is no repsone.
