### ISSUE TITLE
Is it possible to rewrite/format used NFC215 tags?

### ISSUE THREAD

**Issue by lnkpdr** [HiddenRambler/TagMo#49]

**Comment by Bombastisch** [comment]
Nope, because if certain sectors on the Ntag storage are written, they ar not rewrite/ereasable. If you have once written a Amiibo .bin to a Ntag it is not rewriteable.

**Comment by lnkpdr** [comment]
Thanks! Back to amazon to buy some more T_T

**Comment by Bombastisch** [comment]
Yep, thats the thing...   But it has to be like this, because otherwise your real amiibos would be ereasable too!   I still hope for a phone emulation feature, with HCE (host card emulation), but it would need someone with knowledge in this development field.

**Comment by HiddenRambler** [comment]
As @Bombastisch this is not possible due to the way Amiibo's are supposed work.

**Comment by alancnet** [comment]
So why is it an option in the app?

**Comment by Bombastisch** [comment]
There isn't. You probably mean "Restore" which allows you to write to the data section of amiibo.

But you can't change the amiibo type
