### ISSUE TITLE
Issue with writing

### ISSUE THREAD

**Issue by ubbaSWalter** [HiddenRambler/TagMo#50]
I have a Samsung Galaxy 5 
Android version 6.0.1
It will not write to the g215 i bought.

**Comment by quantumfizix** [comment]
What version are you running? Is it giving any errors? Need more information.

**Comment by ubbaSWalter** [comment]
It will just stay on the writing tag screen.  No errors will bob up.  I have tried using the most recent version.

**Comment by HiddenRambler** [comment]
Can you try the latest version?

**Comment by HiddenRambler** [comment]
Closing the issue. If you still have the error please re-open.
