### ISSUE TITLE
Transcieve Failed

### ISSUE THREAD

**Issue by rubenske1** [HiddenRambler/TagMo#51]
when trying to write a Amiibo to NTAG215 it gives the following error:
Error while writing main data (Stage 1)
Java.io.IOException: Transceive failed

running android 7.0 kernel 3.10.61-10958180 at a samsung s6 (model SM-G920F)
Tagmo version 2.3.4 (altered for Samsung)

**Comment by Bombastisch** [comment]
Try using 2.4.0 👍

**Comment by rubenske1** [comment]
tried it on 2.4.0, same error

**Comment by rubenske1** [comment]
correction: is working now. Tried it on a different tag today and is working.... maybe messed up the previous tag.

**Comment by pbhj** [comment]
I've just had the same "transceive" errors. Checking I notice that the supplier has sent me 213 tags instead of 215.
